# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_measures')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_measures')
    _measures = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_measures', [dirname(__file__)])
        except ImportError:
            import _measures
            return _measures
        try:
            _mod = imp.load_module('_measures', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _measures = swig_import_helper()
    del swig_import_helper
else:
    import _measures
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class intArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, intArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, intArray, name)
    __repr__ = _swig_repr

    def __init__(self, nelements):
        this = _measures.new_intArray(nelements)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _measures.delete_intArray
    __del__ = lambda self: None

    def __getitem__(self, index):
        return _measures.intArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _measures.intArray___setitem__(self, index, value)

    def cast(self):
        return _measures.intArray_cast(self)
    if _newclass:
        frompointer = staticmethod(_measures.intArray_frompointer)
    else:
        frompointer = _measures.intArray_frompointer
intArray_swigregister = _measures.intArray_swigregister
intArray_swigregister(intArray)

def intArray_frompointer(t):
    return _measures.intArray_frompointer(t)
intArray_frompointer = _measures.intArray_frompointer

class dlArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, dlArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, dlArray, name)
    __repr__ = _swig_repr

    def __init__(self, nelements):
        this = _measures.new_dlArray(nelements)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _measures.delete_dlArray
    __del__ = lambda self: None

    def __getitem__(self, index):
        return _measures.dlArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _measures.dlArray___setitem__(self, index, value)

    def cast(self):
        return _measures.dlArray_cast(self)
    if _newclass:
        frompointer = staticmethod(_measures.dlArray_frompointer)
    else:
        frompointer = _measures.dlArray_frompointer
dlArray_swigregister = _measures.dlArray_swigregister
dlArray_swigregister(dlArray)

def dlArray_frompointer(t):
    return _measures.dlArray_frompointer(t)
dlArray_frompointer = _measures.dlArray_frompointer


def my_mod(x, y):
    return _measures.my_mod(x, y)
my_mod = _measures.my_mod

def sumitems(first, nitems):
    return _measures.sumitems(first, nitems)
sumitems = _measures.sumitems

def sumfloat(first, nitems):
    return _measures.sumfloat(first, nitems)
sumfloat = _measures.sumfloat

def log2(n):
    return _measures.log2(n)
log2 = _measures.log2

def minVal(arr, nitems):
    return _measures.minVal(arr, nitems)
minVal = _measures.minVal

def maxVal(arr, nitems):
    return _measures.maxVal(arr, nitems)
maxVal = _measures.maxVal

def Entropy(first, nitems, nb):
    return _measures.Entropy(first, nitems, nb)
Entropy = _measures.Entropy

def Mean(ar, n):
    return _measures.Mean(ar, n)
Mean = _measures.Mean

def STD(ar, n):
    return _measures.STD(ar, n)
STD = _measures.STD
# This file is compatible with both classic and new-style classes.


